#!/bin/bash
f1="main.cpp"
f2="vec.cpp"
f3="voxels/voxel.cpp"
f4="voxels/chunk.cpp"
f5="voxels/renderer.cpp"
f6="voxels/worldStream.cpp"

g++ -o game $f1 $f2 $f3 $f4 $f5 $f6 -lraylib -lGL -lm -lpthread -ldl -lrt -lX11